version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      # ... steps for building/testing app ...
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t berviantoleo/flutter-docker:$TAG .     
          # docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
          # docker push berviantoleo/flutter-docker:$TAG
